sudo: required

dist: xenial

before_install:
        - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends \
        texlive-full
script:
        - mkdir _build
        - xelatex -interaction=nonstopmode -halt-on-error -output-directory _build cv_10.tex
#deploy:
#        provider: releases
#        api_key:
#                secure: [YOUR KEY]
#                file:
#                        - _build/cv_10.pdf
#                skip_cleanup: true
#                on:
#                        tags: true
