sudo: required
language: generic
services: docker
script:
- docker pull dxjoke/tectonic-docker
- docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind dxjoke/tectonic-docker
  /bin/sh -c "tectonic cv.tex"
deploy:
  provider: releases
  api_key:
    secure: O+n+dEnA2spPcs7VILfdcJCEB17iedba0r2QvaCsWmW3pMQLTwdlsLyPpfQwIr5kP4MTOoGaWGhWdi5S/wDR9dx3hnve8z00KULpbbetkAqvJWOge/fvHgbECfkKYdUypR3AraWxVITgsFCYW4Rs51NRJ/rPImTK59tMmP7HBhoauuOQpU2Rs1RXodOD27jFT7tLV4qdC0D+iuGNmjbQaJUxHHBCUPD8Nh3j6sJj726rXskUznhhkb7IBfVA68JRsVh1vafBfmBngyatjl7qYjtNQ0svJxRvhJ9W4+L8pWfGV+btTafR3KIqt564q7uKYA7p2Djdl71gT4NrfxoUaMPfIIwRTd82hEWvgzH/TfUSyoBbP2h726ztoORqp3iDxgW6rh/DEBhhDCB+SmkiGlgNdAln8VK4QxVp754FAzsqx87W7XMZZJqsgAMaJnv4jOPlOWEjyTj7a6s6/fOTKZZjl4afmGCTBHddmbV8NuN+cEDHWBnZWlJlwCBVfW0dhR/lBUIyE15NYAkeUzScIDiM0w8GqDkU9FHnqeC8mGD+ldcXEkRyBTplXN0SYhd0mfB/5ARPoMmbbqIcWRFmD148SYqz2KveynVs36vzRe5+nJFsgF2HbyYXpDY3CqXNLcg+GsZ8HftjHGpDlLw1D4sKFs5cAwdgWko4sF/YW3w=
  file: src/cv.pdf
  skip_cleanup: true
  on:
    repo: rngkll/Curriculum
    tags: true
